In [21]:
import os
import glob
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import linear_model, datasets

train_positive_path = '../Sentiment_Analysis/aclImdb/train/pos/'
train_negative_path = '../Sentiment_Analysis/aclImdb/train/neg/'
test_positive_path = '../Sentiment_Analysis/aclImdb/test/pos/'
test_negative_path = '../Sentiment_Analysis/aclImdb/test/neg/'

def read_files_in_path(path):
    positive_training_data=[]
    for filepath in glob.glob(os.path.join(path, '*.txt')):
        with open(filepath,encoding='utf8') as f:
            content = f.read()
            positive_training_data.append(content)
    return positive_training_data
#Read training data
positive_training_data = read_files_in_path(train_positive_path)
print(len(positive_training_data))
negative_training_data = read_files_in_path(train_negative_path)
print(len(negative_training_data))
whole_training_data = positive_training_data+negative_training_data
print(len(whole_training_data))

#Reading Test Data
positive_test_data = read_files_in_path(test_positive_path)
print(len(positive_test_data))
negative_test_data = read_files_in_path(test_negative_path)
print(len(negative_test_data))
whole_test_data = positive_test_data+negative_test_data
print(len(whole_test_data))

12500
12500
25000
12500
12500
25000


In [31]:

train_vectorizer = CountVectorizer()
train_vector = vectorizer.fit_transform(whole_training_data)
test_vector = vectorizer.transform(whole_test_data)
train_labels = np.asarray([1]*len(positive_training_data) + [0]*len(negative_training_data))
test_labels = np.asarray([1]*len(positive_test_data) + [0]*len(negative_test_data))
print(train_labels.shape)
print(train_vector.shape)
print(test_labels.shape)
print(test_vector.shape)
print(train_labels)
print(test_labels)
logreg = linear_model.LogisticRegression()
logreg.fit(train_vector, train_labels)
print("Logistic Regression classification accuracy:\n",logreg.score(test_vector,test_labels)*100,"%")


(25000,)
(25000, 74849)
(25000,)
(25000, 74849)
[1 1 1 ... 0 0 0]
[1 1 1 ... 0 0 0]


C:\Users\MohamedMamdouh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Logistic Regression classification accuracy:
 86.676 %
Prediction
 [1 1 1 ... 1 0 1]
