In [6]:
import os
import glob

train_positive_path = '../Sentiment_Analysis/aclImdb/train/pos/'
train_negative_path = '../Sentiment_Analysis/aclImdb/train/neg/'
test_positive_path = '../Sentiment_Analysis/aclImdb/test/pos/'
test_negative_path = '../Sentiment_Analysis/aclImdb/test/neg/'

def read_files_in_path(path):
    positive_training_data=[]
    for filepath in glob.glob(os.path.join(path, '*.txt')):
        with open(filepath,encoding='utf8') as f:
            content = f.read()
            positive_training_data.append(content)
    return positive_training_data

positive_training_data = read_files_in_path(train_positive_path)


In [7]:
len(positive_training_data)

12500

In [8]:
negative_training_data = read_files_in_path(train_negative_path)
len(negative_training_data)

12500

In [9]:
whole_training_data = positive_training_data+negative_training_data
len(whole_training_data)

25000

In [17]:
# import re
# import numpy

# def word_extraction(sentence):
#     ignore = ['a', "the", "is",]
#     words = re.sub("[^\W]", " ",  sentence).split()
#     cleaned_text = [w.lower() for w in words if w not in ignore]
#     return cleaned_text

# def tokenize(sentences):    
#     words = []    
#     for sentence in sentences:        
#         w = word_extraction(sentence)        
#         words.extend(w)            
#     words = sorted(list(set(words)))    
#     return words

# def generate_bow(allsentences):    
#     vocab = tokenize(allsentences)
#     all_bag_vector = list
#     for sentence in allsentences:
#         words = word_extraction(sentence)
#         bag_vector = numpy.zeros(len(vocab))
#         for w in words:
#             for i,word in enumerate(vocab):
#                 if word == w: 
#                     bag_vector[i] += 1
#         all_bag_vector.append(list(bag_vector))
#     return all_bag_vector
# bag_of_words = generate_bow(whole_training_data)
# print(bag_of_words)

from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(whole_training_data)
print(X.toarray())


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
